name:                EchoBot
version:             0.0.0.1
github:              "Slaopir/EchoBot"
license:             MIT
author:              "Slaopir"
maintainer:          "salopir99@gmail.com"
copyright:           "2021 Slaopir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EchoBot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  EchoBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot

tests:
  EchoBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EchoBot
